"""add lat_lng to entities

Revision ID: bce7de430380
Revises: 5dc6d64485bb
Create Date: 2026-06-08 19:59:59.124576

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bce7de430380'
down_revision: Union[str, Sequence[str], None] = '5dc6d64485bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('entities', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'longitude')
    op.drop_column('entities', 'latitude')
    # ### end Alembic commands ###
